---
title: "explore-ideas"
output: html_document
---

```{r}
library(tidyverse)
experiencesdashboard::sentiment_txt_data

rolling_mean <- tibbletime::rollify(mean, window = 30)

sentiment_txt_data_tidy <- experiencesdashboard::sentiment_txt_data %>% 
  dplyr::mutate(date = lubridate::date(date),
                year = lubridate::year(date),
                id = 1:nrow(sentiment_txt_data),
                all_sentimtents_unnest = all_sentiments) %>% 
  dplyr::select(id, date, year, super, division2, improve, all_sentiments, 
                all_sentimtents_unnest) %>% 
  tidyr::unnest(cols = all_sentimtents_unnest) %>% 
  dplyr::distinct() %>% 
  dplyr::mutate(value = TRUE) %>% 
  tidyr::pivot_wider(id_cols = c("id", "date", "year", "super", "division2", 
                                 "improve", "all_sentiments"), 
                     names_from = all_sentimtents_unnest, 
                     values_from = value) %>% 
  janitor::clean_names() %>% 
  dplyr::select(-na) %>%
  tidyr::replace_na(list(trust = FALSE, 
                         anticipation = FALSE, 
                         positive = FALSE, 
                         negative = FALSE, 
                         sadness = FALSE, 
                         fear = FALSE, 
                         joy = FALSE,
                         anger = FALSE, 
                         disgust = FALSE, 
                         surprise = FALSE)
  ) %>% 
  dplyr::mutate_if(is.logical, as.numeric)

mean_data <- purrr::map(c("anger", "anticipation", "disgust", "fear", "joy", "negative", 
                          "positive", "sadness", "surprise", "trust"), function(x) {
                            
                            tidydata %>% 
                              dplyr::group_by(date) %>%
                              dplyr::summarise(var_sum = sum(.data[[x]], na.rm = TRUE)) %>% 
                              dplyr::ungroup() %>%  
                              tsibble::tsibble(index = date) %>% 
                              tsibble::fill_gaps(var_sum = 0) %>% 
                              as.data.frame() %>% 
                              dplyr::mutate(roll_var = rolling_mean(var_sum)) %>% 
                              dplyr::select(roll_var) %>% 
                              purrr::set_names(x)
                          }) %>% 
  do.call(cbind, .)
```


```{r}
to_plot <- dplyr::bind_cols(
        tidydata %>% 
          dplyr::group_by(date) %>%
          dplyr::summarise(var_sum = sum(anger, na.rm = TRUE)) %>% 
          dplyr::ungroup() %>%  
          tsibble::tsibble(index = date) %>% 
          tsibble::fill_gaps(var_sum = 0) %>% 
          as.data.frame() %>% 
          dplyr::select(date),
        as.data.frame(prop.table(as.matrix(mean_data), 1) * 100)
        )
      
whats_this <- to_plot %>% 
        tidyr::drop_na() %>% 
        tidyr::pivot_longer(-date)
        ggplot2::ggplot(ggplot2::aes(x = date, 
                                     y = value, 
                                     colour = name, 
                                     group = name)) +
        ggplot2::geom_line()


experiencesdashboard::tidy_trust_data


```













```{r}
library(tidyverse)

sentiments <- c("anticipation", "positive", "negative", "sadness", "fear", "joy", "anger", "disgust", "surprise")

sentiment_txt_data_tidy %>% 
  select(date, super, division2, 
         anticipation, positive, negative, sadness, fear, joy, anger, disgust, surprise) %>% 
  pivot_longer(cols = c(sentiments), 
               names_to = "sentiment_name", 
               values_to = "sentiment_check") %>% 
  group_by(date, super, division2) %>% 
  mutate(sum_sentiments = sum(sentiment_check))


sentiment_txt_data_tidy %>% 
        tidyr::unnest(cols = all_sentiments) %>% 
        # dplyr::filter(all_sentiments %in% input$select_sentiment_plot) %>% 
        dplyr::select(date, all_sentiments, super, division2) %>% 
        tidyr::drop_na() %>% 
  dplyr::arrange(date, super, division2) %>% 
  dplyr::group_by(date) %>% 
  dplyr::mutate(n_sent_distinct = n_distinct(all_sentiments))
```





```{r}
filtered_comments <- sentiment_txt_data_tidy %>% 
        dplyr::select(id, all_sentiments, improve) %>% 
        # First get number of total sentiments in all comments
        dplyr::mutate(length = lengths(all_sentiments),
                      all_sentimtents_unnest = all_sentiments) %>%
        # Now filter for number of selected sentiments
        dplyr::filter(length == length(input$select_sentiment_txt)) %>%
        # Unnest to create long version of data
        tidyr::unnest(cols = all_sentimtents_unnest) %>% 
        # Group by comment id so that every computation is now for each comment
        dplyr::group_by(id) %>% 
        dplyr::mutate(test_sentiment = dplyr::case_when(
          all_sentimtents_unnest %in% input$select_sentiment ~ TRUE),
          sum_temp = sum(test_sentiment)) %>% 
        dplyr::ungroup() %>% 
        # Filter comments that match the selected sentiments
        dplyr::filter(is.na(sum_temp) == FALSE) %>% 
        dplyr::select(id, improve) %>%
        dplyr::distinct()
```










```{r}
#ADD CHRIS ROLLING MEAN LINE GRAPH HERE

    
    # Define rolling mean function
    # rolling_mean <- tibbletime::rollify(mean, window = 30)
    # 
    # output$sentiment_line_graph <- renderPlot({
    #   
    #   mean_data <- purrr::map(c("anger", "anticipation", "disgust", "fear", "joy", "negative", 
    #                             "positive", "sadness", "surprise", "trust"), function(x) {
    #                               
    #                               sentiment_txt_data_tidy_r() %>% 
    #                                 dplyr::group_by(date) %>%
    #                                 dplyr::summarise(var_sum = sum(.data[[x]], na.rm = TRUE)) %>% 
    #                                 dplyr::ungroup() %>%  
    #                                 tsibble::tsibble(index = date) %>% 
    #                                 tsibble::fill_gaps(var_sum = 0) %>% 
    #                                 as.data.frame() %>% 
    #                                 dplyr::mutate(roll_var = rolling_mean(var_sum)) %>% 
    #                                 dplyr::select(roll_var) %>% 
    #                                 purrr::set_names(x)
    #                             }) %>% 
    #     do.call(cbind, .)
    #   
    #   to_plot <- dplyr::bind_cols(
    #     sentiment_txt_data_tidy_r() %>% 
    #       dplyr::group_by(date) %>%
    #       dplyr::summarise(var_sum = sum(anger, na.rm = TRUE)) %>% 
    #       dplyr::ungroup() %>%  
    #       tsibble::tsibble(index = date) %>% 
    #       tsibble::fill_gaps(var_sum = 0) %>% 
    #       as.data.frame() %>% 
    #       dplyr::select(date),
    #     as.data.frame(prop.table(as.matrix(mean_data), 1) * 100)
    #     )
    #   
    #   to_plot %>% 
    #     tidyr::drop_na() %>% 
    #     tidyr::pivot_longer(-date) %>% 
    #     ggplot2::ggplot(ggplot2::aes(x = date, 
    #                                  y = value, 
    #                                  colour = name, 
    #                                  group = name)) +
    #     ggplot2::geom_line()
    #   
    # })
```





```{r}
experiencesdashboard::sentiment_txt_data %>% 
  mutate(date = lubridate::as_date(date)) %>% 
  tidyr::unnest(cols = all_sentiments) %>% 
  dplyr::select(date, all_sentiments) %>% 
  tidyr::drop_na() %>% 
  # dplyr::mutate(all_sentiments = factor(x = all_sentiments,
  #                                       levels = sentiments_ordered,
  #                                       labels = sentiments_ordered_sentence)) %>%
  # dplyr::mutate(all_sentiments = dplyr::case_when(all_sentiments %in% input$select_sentiment_plot ~ all_sentiments,
  #                                                 TRUE ~ NA_character_),
  #               all_sentiments = stringr::str_to_sentence(all_sentiments)) %>% 
  ggplot2::ggplot(ggplot2::aes(date, 
                               fill = all_sentiments,
                               colour = all_sentiments)) +
  ggplot2::geom_density(alpha = .1, size = 1) +
  # ggplot2::geom_histogram(position = "fill") +
  # ggplot2::geom_freqpoly(ggplot2::aes(y = ..prop..)) +
  # ggplot2::scale_x_date() +
  # ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  ggplot2::scale_fill_viridis_d(direction = -1) +
  ggplot2::scale_colour_viridis_d(direction = -1) +
  ggplot2::labs(x = "Date", 
                y = NULL, 
                fill = "Selected\nsentiments",
                colour = "Selected\nsentiments") +
  ggplot2::theme(text = ggplot2::element_text(size = 16))
```




```{r}

filter_date_start <- "2018-01-02"
filter_date_end <- "2020-12-02"

filter_TeamN <- c("CAMHS Crisis", "The Orion Unit")
filter_Directorate2 <- c("Adult mental health")
filter_Division2 <- c("Local partnerships- MH")

df_filtered <- tidy_trust_data %>% 
  filter(between(x = date, 
                 left = as.Date(filter_date_start), 
                 right = as.Date(filter_date_end)))# %>% 
  # filter(TeamN %in% c(filter_TeamN)) %>% 
  # filter(Directorate2 %in% c(filter_Directorate2)) %>% 
  # filter(Division2 %in% c(filter_Division2))
```


```{r}

library(patchwork)
df_filtered %>% 
  group_by(super_category, comment_type) %>% 
  summarise(n = n(),
            crit_mean = mean(crit, na.rm = T),
            crit_sd = sd(crit, na.rm = T))

select_category <- c("Access to Services", "Care/ Treatment", "Communication", "Staff/ Staff Attitude")

plot1 <- tidy_trust_data %>% 
  drop_na(crit) %>% 
  filter(super_category %in% {{select_category}}) %>% 
  select(date, crit, super_category, comment_type) %>% 
  ggplot(aes(x = date, fill = factor(crit))) +
  geom_histogram(position = "stack") +
  # geom_density(position = "fill", ) +
    facet_grid(super_category ~ factor(comment_type, 
                                     levels = c("best", "improve"),
                                     labels = c("What was good?", "What could we do better?"))) +
  scale_fill_viridis_d() +
  labs(x = "Date", 
       y = "Number of responses", 
       fill = "Criticality")

# ?geom_histogram
plot1

plot2 <- tidy_trust_data %>% 
  drop_na(crit) %>% 
  filter(super_category %in% {{select_category}}) %>% 
  select(date, crit, super_category, comment_type) %>% 
  ggplot(aes(x = date, fill = factor(crit))) +
  geom_histogram(position = "fill") +
  ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  facet_grid(super_category ~ factor(comment_type, 
                                     levels = c("best", "improve"),
                                     labels = c("What was good?", "What could we do better?"))) +
  scale_fill_viridis_d() +
  labs(x = "Date", 
       y = "Percentage of responses", 
       fill = "Criticality")

plot2


plot1 + plot2

plotly::ggplotly(plot)

# what are meaningful time periods of the year in case I need to categorise
# what does 1 to 3 mean again 

```

